const header=document.querySelector('.site-header');
const menuToggle=document.querySelector('.menu-toggle');
function setMenu(open){if(!header||!menuToggle)return;header.classList.toggle('menu-open',open);document.body.classList.toggle('menu-active',open);menuToggle.setAttribute('aria-expanded',String(open));menuToggle.setAttribute('aria-label',open?'Close navigation':'Open navigation');}
menuToggle?.addEventListener('click',()=>setMenu(!header.classList.contains('menu-open')));
document.querySelectorAll('.main-nav a,.main-nav button').forEach(el=>el.addEventListener('click',()=>setMenu(false)));
window.addEventListener('resize',()=>{if(window.innerWidth>700)setMenu(false);});

const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target);}}),{threshold:.12});
document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));

const industryData={property:{title:'Estate Agency Workspace',description:'Manage properties, tenants, landlords, maintenance and compliance without losing the full history.',metrics:[['Open maintenance','14'],['Certificates due','6'],['Rent follow-ups','3']],items:['Full property and contact history','Automated compliance reminders','Context-aware email drafting','One timeline for every property']},accounting:{title:'Accounting Practice Workspace',description:'Keep clients, deadlines, payroll, VAT, AML and HMRC work together in one organised system.',metrics:[['Deadlines this week','18'],['Payrolls due','4'],['Client queries','9']],items:['Client records and document requests','VAT and payroll deadline tracking','AML and due diligence workflows','AI-assisted client communication']},marketing:{title:'Marketing Agency Workspace',description:'Connect leads, clients, campaigns, approvals, files and performance in one clear workspace.',metrics:[['Active campaigns','12'],['Approvals waiting','7'],['Leads this month','36']],items:['Campaign and project visibility','Client approval workflows','Shared files and communications','Automated reporting reminders']},services:{title:'Professional Services Workspace',description:'Manage clients, projects, documents, billing and follow-ups without adding unnecessary complexity.',metrics:[['Active clients','42'],['Open projects','11'],['Invoices due','8']],items:['Connected client and project records','Simple document organisation','Billing and follow-up visibility','Flexible workflows for your team']}};
const preview=document.getElementById('industryPreview');
document.querySelectorAll('[data-industry]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-industry]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const d=industryData[btn.dataset.industry];if(preview)preview.innerHTML=`<div class="preview-top"><span class="status">LIVE WORKSPACE</span><span>Today</span></div><h3>${d.title}</h3><p>${d.description}</p><div class="preview-columns">${d.metrics.map(m=>`<div><small>${m[0]}</small><strong>${m[1]}</strong></div>`).join('')}</div><ul>${d.items.map(i=>`<li><span>✓</span>${i}</li>`).join('')}</ul>`;}));

const aiAnswers={priorities:['Today\'s priority summary','3 urgent tasks, 2 payment follow-ups and 1 document awaiting action.'],draft:['Client update draft','I have prepared a concise update using the latest activity and the recommended next step.'],compliance:['Compliance attention required','2 records are overdue and 4 certificates are due within the next 30 days.']};
document.querySelectorAll('[data-ai]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-ai]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const answer=aiAnswers[btn.dataset.ai];const box=document.getElementById('aiAnswer');if(box)box.innerHTML=`<b>${answer[0]}</b><p>${answer[1]}</p>`;}));

const modal=document.getElementById('modal');const modalContent=document.getElementById('modalContent');
function openModal(type){const template=document.getElementById(`${type}Template`);if(!template||!modal||!modalContent)return;setMenu(false);modalContent.innerHTML='';modalContent.appendChild(template.content.cloneNode(true));modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';bindForms();modalContent.querySelector('input,select,textarea')?.focus();}
function closeModal(){if(!modal)return;modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow='';}
document.querySelectorAll('[data-modal]').forEach(btn=>btn.addEventListener('click',()=>openModal(btn.dataset.modal)));
document.querySelectorAll('[data-close]').forEach(btn=>btn.addEventListener('click',closeModal));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();setMenu(false);}});
function success(formType){const titles={demo:'Your demo request is ready.',quote:'Your quote request is ready.'};modalContent.innerHTML=`<div class="success-message"><div class="success-icon">✓</div><h2>${titles[formType]||'Thank you.'}</h2><p>This launch foundation does not transmit data yet. Connect the approved Supabase or email backend before publishing the form.</p><button class="btn btn-primary" data-close>Close</button></div>`;modalContent.querySelector('[data-close]')?.addEventListener('click',closeModal);}
function bindForms(){modalContent?.querySelectorAll('form[data-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();success(form.dataset.form);}));}
document.querySelectorAll('main form[data-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();openModal(form.dataset.form==='quote'?'quote':'demo');setTimeout(()=>success(form.dataset.form),120);}));

const counters=document.querySelectorAll('[data-count]');const counterObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;const el=entry.target;const target=Number(el.dataset.count);let value=0;const step=Math.max(1,Math.ceil(target/18));const timer=setInterval(()=>{value=Math.min(target,value+step);el.textContent=value;if(value>=target)clearInterval(timer);},45);counterObserver.unobserve(el);}),{threshold:.7});counters.forEach(el=>counterObserver.observe(el));


// Estavo v1.2.0 Product Experience tabs
const experienceData = {
 dashboard:{title:'Good morning, Barbara',metrics:[['Properties','248','12 added this year'],['Active tenants','236','98.9% occupied'],['Open maintenance','6','2 require attention'],['Compliance due soon','11','Next 30 days']],text:'Your portfolio is performing well. Six items need attention today, including two compliance deadlines and one rent follow-up.'},
 properties:{title:'Property portfolio',metrics:[['Managed properties','248','Across 7 areas'],['Available','9','Ready to market'],['Occupied','236','95.2% of portfolio'],['Inspections due','14','This month']],text:'Three properties need marketing updates and two inspections should be booked this week.'},
 compliance:{title:'Compliance overview',metrics:[['Total records','248','All properties linked'],['Active','229','92.3% compliant'],['Due soon','11','Next 30 days'],['Expired','8','Action required']],text:'Eight certificates require action. Estavo has grouped them by urgency and assigned the next steps.'},
 finance:{title:'Finance visibility',metrics:[['Rent due','£242,500','This month'],['Received','£239,950','98.9% collected'],['Outstanding','£2,550','5 tenancies'],['Collection rate','98.9%','Up 1.2%']],text:'Collection is ahead of last month. Five balances remain outstanding, with reminders ready to send.'},
 users:{title:'Users & roles',metrics:[['Active users','5','All verified'],['Administrators','2','Full access'],['Property managers','2','Portfolio access'],['Read-only users','1','Reporting access']],text:'Roles keep sensitive actions controlled while every team member sees the information needed for their work.'}
};
document.querySelectorAll('[data-experience]').forEach(btn=>btn.addEventListener('click',()=>{
 document.querySelectorAll('[data-experience]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');
 const d=experienceData[btn.dataset.experience]; const title=document.getElementById('experienceTitle'); const metrics=document.getElementById('experienceMetrics'); const text=document.getElementById('experienceText');
 if(title) title.textContent=d.title; if(text) text.textContent=d.text; if(metrics) metrics.innerHTML=d.metrics.map(m=>`<article><small>${m[0]}</small><strong>${m[1]}</strong><span>${m[2]}</span></article>`).join('');
}));
